#!/usr/local/bin/bash
# Arrays of sheetID and sheet names, indexed by teachers name
echo "Hello from script test"
declare -A sheetID
declare -A sheetName
sheetID[Grace]=1fLDy8hmgYdxYvQPhbi6DFL0BqR8hvlvK2YaA7vgoEzc
sheetName[Grace]=GracesClass
echo "sheetID test" ${sheetID[Grace]}
echo "sheetName test" ${sheetName[Grace]}

if [[ $# -ne 1 ]]
then
	echo "Must have 1 argument: Month abbreviation"
else
	echo "Processing for month ${1}"
	# python3 main.py --SheetID=1fLDy8hmgYdxYvQPhbi6DFL0BqR8hvlvK2YaA7vgoEzc --SheetName=GracesClass --Mode=Preview --Month=Jan
fi
