#!/usr/local/bin/bash
# Need bash 4 or greater.
# Argument 1 is teacher, which must be 'Grace', 'Mythili', or 'Teacher'
# Argument 2 is mode, which must be 'Preview' or 'Live'.
# Argument 3 is month abbreviation, e.g. Jan, Feb.
teacher=$1
mode=$2
month=$3

# Arrays of sheetID and sheet names, indexed by teachers name.
declare -A sheetID
declare -A sheetName
declare -A modes=([Preview]=1 [Live]=2)
declare -A months=([Jan]=1 [Feb]=2 [Mar]=3 [Apr]=4 [May]=5 [Jun]=6 [Jul]=7 [Aug]=8 [Sep]=9 [Oct]=10 [Nov]=11 [Dec]=12)

# Initialize sheet ids and sheet names within the Google sheets.
sheetID[Grace]=1fLDy8hmgYdxYvQPhbi6DFL0BqR8hvlvK2YaA7vgoEzc
sheetName[Grace]=GracesClass
sheetID[Mythili]=1MolY8_4Ze-g8vxVhd9MLg0yCq8asqY-JAk4q673zlf8
sheetName[Mythili]=MythilisClass
sheetID[Lakshmi]=1EXk6GIdfHvA3vwySgtIKjP8KCeVNLxbfZO_761FkmiI
sheetName[Lakshmi]=Lakshmi

if [[ $# -ne 3 ]]
then
	echo "Must have 3 arguments:"
	echo "Arg1 is teacher (Grace, Mythili, or Lakshmi)"
	echo "Arg2 is mode (Preview or Live)"
	echo "Arg3 month abbreviation (e.g. Jan, Feb ...)"
	exit 4
fi

# Validate the arguments
if [[ -v "modes[$mode]"  && -v "months[$month]" ]]
then
	if [[ -v "sheetID[$teacher]" && "sheetName[$teacher]" ]]
	then
		sheetid=${sheetID[$teacher]}
		sheetname=${sheetName[$teacher]}
		echo "Processing for teacher ${1} in mode ${2} for month ${1},"
		echo "using sheetid=$sheetid"
		echo "and sheetname=$sheetname"
	  python3 main.py --SheetID=$sheetid --SheetName=$sheetname --Mode=$mode --Month=$month
	else
		echo "sheetID and/or sheetName does not exist for $teacher"
	fi
else
	echo "Could not find either $mode or $month"
  exit 2
fi
